<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="preload" href="CSS/normalize.css" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https: //fonts.googleapis.com/css2? family = Krub & display = swap " rel=" stylesheet " />
  <link rel="preload" href="CSS/estilos.css" as="styles" />
  <link rel="stylesheet" href="CSS/estilos.css" />

</head>

<body>
  <header class="header">
    <center>
      <h1><span>Ups! algo salio mal!</span></h1>
    </center>
  </header>

  <div class="img1">
    <div style="border: 2px solid brown;
    border-radius: 25px;">
      <h2>En este momento no hay servidores disponibles para artender su solicitud, por favor intente mas tarde.</h2>


    </div>
  </div>

  <footer class="footer">
    <p>© todos los derechos reservados </p>
  </footer>
</body>

</html>